---
- hosts: all
  become: true
  vars:
    MySQL_root_pass: root
  tasks:
    - name: Update APT-Cache
      apt: update_cache=yes

    - name: Install Ubuntu dependencies
      apt: name={{ item }}
      with_items:
        - php5
        - nginx
        - php5-cli
        - php5-curl
        - php5-mysql
        - php5-fpm
        - python-mysqldb

    - name: Install MySQL
      apt: package=mysql-server state=installed force=yes update_cache=yes cache_valid_time=3600

    - name: Create the nginx vhost
      copy: src=conf/{{ env }}/nginx dest=/etc/nginx/sites-enabled/{{ project_name }}

    - name: Restart nginx
      service: name=nginx state=restarted

    - name: Create MySQL database
      mysql_db: name={{ project_name }} state=present login_user=root

    - name: Load backup
      mysql_db: name={{ project_name }} state=import target={{ path }}/conf/{{ env }}/dump.sql

    - name: Update the WP config file
      copy: src=conf/{{ env }}/wp-config.php dest={{ path }}






